#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/watchyourlan
DATA_DIR=/etc/watchyourlan

start_service() {
	[ -s "$DATA_DIR/config_v2.yaml" ] || {
		logger -t watchyourlan "Missing $DATA_DIR/config_v2.yaml"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG" -d "$DATA_DIR"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
