include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-watchyourlan
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for WatchYourLAN
LUCI_DESCRIPTION:=LuCI menu entry for WatchYourLAN
LUCI_DEPENDS:=+watchyourlan
PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
